name: Sync

on:
  push:
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        gitee-username: lvyhan
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: lvyhan/lvyhan
        branch: master